kind = "api"
previewPath = "/api"
title = "API Server"
version = "1.0.0"
id = "3B4_FFSkEVBkAeYMFRJ2e"

[[services]]
localPort = 8080
name = "API Server"
paths = ["/api"]

[services.development]
run = "mvn -f /home/runner/workspace/artifacts/api-server/pom.xml spring-boot:run -q"

[services.production]

[services.production.build]
args = ["mvn", "-f", "/home/runner/workspace/artifacts/api-server/pom.xml", "package", "-DskipTests", "-q"]

[services.production.run]
args = ["java", "-jar", "/home/runner/workspace/artifacts/api-server/target/lingua-api-server-0.0.1-SNAPSHOT.jar"]

[services.production.run.env]
PORT = "8080"

[services.production.health.startup]
path = "/api/healthz"
